version: "3.4"
services:

  frontend: 
    build: frontend
    ports:
      - 8080:80
    depends_on:
      - db
      - backend
    links:
      - db
      - backend

  backend: 
    build: backend
    ports:
      - 9000:9000
    depends_on:
      - db
    links:
      - db
    restart: on-failure

  db: 
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: "no"
    environment: 
      MYSQL_DATABASE: "interests"
      MYSQL_USER: "user" 
      MYSQL_PASSWORD: "password" 
      MYSQL_ROOT_PASSWORD: "root" 
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u user --password=password; echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      interval: 10s
      timeout: 10s
      retries: 30

